#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Ensure Jenkins Home dir exists with correct ownership
  file: path="{{jenkins_home_path}}" owner="{{ansible_ssh_user}}" state=directory

- name: Docker requires docker-py
  pip: name=docker-py

- name: Jenkins Container
  docker:
    name: "{{jenkins_container_name}}"
    image: openedge/jenkins
    state: reloaded
    ports:
    - "8080:8080"
    volumes:
    - "{{jenkins_home_path}}:/var/jenkins_home"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "$(which docker):/usr/bin/docker"

- name: specify additional plugin scm-api
  lineinfile: dest={{jenkins_home_path}}/plugins.txt line="scm-api" create="yes"

- name: install additional plugins
  sudo: yes
  command: "docker exec -t {{jenkins_container_name}} /usr/local/bin/plugins.sh /var/jenkins_home/plugins.txt"




